language: python
python:
  - 2.7
  - 3.5
  - pypy
install:
  - pip install -r requirements.txt
  - pip install coveralls
after_success:
  coveralls
script:
  - nosetests --with-coverage --cover-package=bashql
