language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
after_success:
  coveralls
# command to run tests
script:
  - nosetests --with-coverage --cover-package=bashql
